In [53]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import r2_score

In [11]:
df = pd.read_csv('BostonHousing.csv')
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0


In [12]:
df.shape

(506, 14)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64  
 4   nox      506 non-null    float64
 5   rm       501 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64  
 9   tax      506 non-null    int64  
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [14]:
df.isna().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         5
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [15]:
rm_median = df['rm'].median()

In [16]:
df['rm'] = df['rm'].fillna(rm_median)

In [17]:
df.isna().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [18]:
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0


In [26]:
x = df.iloc[:, 0:13]
y = df.iloc[:, -1]

In [27]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [28]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
x_scaled = std.fit_transform(x)

In [29]:
x_scaled

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [39]:
# Dataset Split
from sklearn.model_selection import train_test_split as tts
xtrain, xtest, ytrain, ytest = tts(x_scaled, y, test_size=0.2, random_state=42)

In [40]:
xtrain.shape

(404, 13)

In [41]:
xtest.shape

(102, 13)

In [42]:
ytest.shape

(102,)

In [43]:
ytrain.shape

(404,)

In [44]:
# Apply Linear Regression
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(xtrain, ytrain)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [45]:
lr.score(xtrain, ytrain)

0.7506143967274728

In [46]:
lr.score(xtest, ytest)

0.6665030487253161

In [47]:
ypred = lr.predict(xtest)
ypred

array([28.98569055, 36.00706941, 14.84438855, 25.02061382, 18.77386209,
       23.26220973, 17.6698461 , 14.3512927 , 23.02076629, 20.62526059,
       24.91948199, 18.66813486, -6.08246257, 21.76741109, 19.23854195,
       26.18956521, 20.66161361,  5.80148502, 40.49123015, 17.61851042,
       27.22842262, 30.04981803, 11.3475005 , 24.14676372, 17.85996976,
       15.84151224, 22.78020868, 14.57840365, 22.44477547, 19.18900883,
       22.42609485, 25.20991744, 25.93635035, 17.69976563, 16.77713405,
       16.96421169, 31.2317762 , 20.12060928, 23.76612789, 24.62158601,
       13.93830377, 32.23403436, 42.66084543, 17.33140543, 27.26044028,
       16.99500643, 14.07051828, 25.89261304, 20.30167196, 29.94677248,
       21.3125114 , 34.33708037, 16.04936489, 26.21092456, 39.5247777 ,
       22.58090068, 18.84854949, 32.70596651, 25.05791007, 12.90965247,
       20.2305824 , 30.48462009, 31.4999042 , 15.88082103, 20.2459958 ,
       16.72434534, 20.52551387, 25.95161425, 30.59728637, 11.59

In [55]:
# Model Evaluation
r2_score(ytest, ypred)

0.6665030487253161

In [70]:
# Apply Lasso Regression
from sklearn.linear_model import Lasso
ls = Lasso(alpha=0.1)

In [71]:
ls.fit(xtrain, ytrain)

,alpha,0.1
,fit_intercept,True
,precompute,False
,copy_X,True
,max_iter,1000
,tol,0.0001
,warm_start,False
,positive,False
,random_state,None
,selection,'cyclic'


In [72]:
ls.score(xtrain, ytrain)

0.7447194853029862

In [73]:
ls.score(xtest, ytest)

0.6472594441868946

In [74]:
ls_pred = ls.predict(xtest)
ls_pred

array([28.61448643, 34.62181726, 17.6075683 , 24.88135199, 18.58555064,
       23.73132469, 17.9831847 , 15.03401737, 22.34587367, 20.96205434,
       24.11096526, 19.4176244 , -5.25766315, 22.4452208 , 19.36856826,
       25.6556095 , 19.20165709,  5.38763912, 39.15440167, 17.53381804,
       26.25961923, 28.70696277, 12.08120832, 24.39169654, 17.60258796,
       15.17614192, 23.08381547, 15.07934257, 22.23828105, 19.57519617,
       21.91530406, 25.25645818, 25.86251519, 17.43070308, 16.16790351,
       17.91981437, 31.60306049, 19.94990164, 23.52200989, 24.52751134,
       14.24071346, 30.45246948, 40.50696753, 18.00732714, 27.30410856,
       16.56491274, 14.63701259, 25.82112463, 19.74652122, 30.51403825,
       21.89026926, 33.33596063, 16.7106224 , 26.78950786, 38.61674462,
       22.20472702, 18.66838447, 30.94183457, 25.07105933, 13.58173661,
       20.34766862, 29.58898711, 30.53958173, 16.10653524, 22.49108501,
       16.46416505, 20.20396666, 25.63644513, 29.29007976, 11.79

In [75]:
r2_score(ytest, ls_pred)

0.6472594441868946

In [76]:
import numpy as np
ls = Lasso()
para = {'alpha' : np.logspace(-1, 10, 1000)}
para

{'alpha': array([1.00000000e-01, 1.02567793e-01, 1.05201522e-01, 1.07902879e-01,
        1.10673602e-01, 1.13515471e-01, 1.16430313e-01, 1.19420003e-01,
        1.22486461e-01, 1.25631660e-01, 1.28857621e-01, 1.32166418e-01,
        1.35560179e-01, 1.39041083e-01, 1.42611371e-01, 1.46273336e-01,
        1.50029332e-01, 1.53881775e-01, 1.57833141e-01, 1.61885969e-01,
        1.66042866e-01, 1.70306503e-01, 1.74679622e-01, 1.79165033e-01,
        1.83765620e-01, 1.88484341e-01, 1.93324229e-01, 1.98288395e-01,
        2.03380031e-01, 2.08602409e-01, 2.13958887e-01, 2.19452909e-01,
        2.25088005e-01, 2.30867799e-01, 2.36796007e-01, 2.42876438e-01,
        2.49113003e-01, 2.55509709e-01, 2.62070670e-01, 2.68800102e-01,
        2.75702333e-01, 2.82781798e-01, 2.90043049e-01, 2.97490755e-01,
        3.05129702e-01, 3.12964801e-01, 3.21001090e-01, 3.29243733e-01,
        3.37698031e-01, 3.46369418e-01, 3.55263468e-01, 3.64385898e-01,
        3.73742574e-01, 3.83339510e-01, 3.93182876e-01,

In [77]:
# GridSearchCV
from sklearn.model_selection import GridSearchCV
gsc = GridSearchCV (ls, para, cv = 8, scoring="neg_mean_absolute_error")
gsc.fit(xtrain, ytrain)

,estimator,Lasso()
,param_grid,{'alpha': array([1.0000...00000000e+10])}
,scoring,'neg_mean_absolute_error'
,n_jobs,None
,refit,True
,cv,8
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,alpha,0.11942000281335322


In [78]:
best_para = gsc.best_params_
best_para

{'alpha': 0.11942000281335322}

In [79]:
gsc.score(xtrain, ytrain)

-3.2743179775820805

In [80]:
gsc.score(xtest, ytest)

-3.299958903717942

In [81]:
gsc_pred = gsc.predict(xtest)
gsc_pred

array([28.48516571, 34.37762387, 18.16949796, 24.93055158, 18.54958044,
       23.8285386 , 18.02810038, 15.21289602, 22.22218117, 20.99659577,
       23.95831277, 19.53081636, -5.11659126, 22.60646536, 19.36588915,
       25.59119857, 19.03225738,  5.29182302, 38.90428974, 17.51002728,
       26.12519649, 28.48077586, 12.17850626, 24.45661222, 17.54188113,
       15.03849749, 23.18496328, 15.17131931, 22.17632034, 19.62601854,
       21.74655359, 25.27001567, 25.85871057, 17.35036965, 16.05229581,
       18.10806918, 31.68073212, 19.91512642, 23.48981869, 24.59140584,
       14.27307328, 30.07808641, 40.12689063, 18.13522455, 27.27041545,
       16.46890717, 14.6971395 , 25.89089865, 19.65333235, 30.56586975,
       21.97086322, 33.15862591, 16.80077315, 26.87851999, 38.43647559,
       22.17947057, 18.62173906, 30.63517412, 25.0688473 , 13.68000299,
       20.37430866, 29.43991167, 30.38610838, 16.15704714, 22.88435344,
       16.3789056 , 20.1387762 , 25.58620523, 29.05554542, 11.82

In [82]:
r2_score(ytest, gsc_pred)

0.6407716824635512